import type { NodeType } from "./types";

export interface NodeSchema {
  config_schema: { type: string; properties: Record<string, any> };
  default_config: Record<string, any>;
  validation_rules: Record<string, any>;
  output_schema: { fields: Record<string, string> };
  visual: { color: string; group: string; icon?: string };
}

export const FALLBACK_SCHEMAS: Record<NodeType, NodeSchema> = {
  Sequential: { config_schema: { type: "object", properties: {} }, default_config: {}, validation_rules: {}, output_schema: { fields: {} }, visual: { color: "#6b7280", group: "control", icon: "ListOrdered" } },
  Parallel: { config_schema: { type: "object", properties: { join: { type: "string", enum: ["all", "any", "first_n"] }, n: { type: "integer", minimum: 1 } } }, default_config: { join: "all" }, validation_rules: { enums: { join: ["all", "any", "first_n"] } }, output_schema: { fields: { children_results: "array" } }, visual: { color: "#6b7280", group: "control", icon: "Columns" } },
  Loop: { config_schema: { type: "object", properties: { max_iterations: { type: "integer", minimum: 1, maximum: 1000, default: 100 }, condition: { type: "string", format: "textarea" }, body: { type: "array", items: { type: "string" } } } }, default_config: { max_iterations: 100 }, validation_rules: { ranges: { max_iterations: { min: 1, max: 1000 } } }, output_schema: { fields: {} }, visual: { color: "#6b7280", group: "control", icon: "Repeat" } },
  Branch: { config_schema: { type: "object", properties: { cases: { type: "object", additionalProperties: { type: "string", format: "textarea" } }, default: { type: "string" } } }, default_config: {}, validation_rules: {}, output_schema: { fields: {} }, visual: { color: "#6b7280", group: "control", icon: "GitBranch" } },
  HITL: { config_schema: { type: "object", properties: { actions: { type: "array", items: { type: "string", enum: ["approve", "edit", "reject", "reroute"] } }, title: { type: "string" }, description: { type: "string", format: "textarea" }, form: { type: "object" }, timeout_seconds: { type: "integer", minimum: 1 }, reject_branch: { type: "string" } } }, default_config: { actions: ["approve", "edit", "reject", "reroute"] }, validation_rules: { non_empty_if_set: ["actions"] }, output_schema: { fields: { action: "string", value: "any" } }, visual: { color: "#eab308", group: "control", icon: "🔶" } },
  LLM: { config_schema: { type: "object", properties: { template: { type: "string", format: "textarea" }, prompt: { type: "string", format: "textarea" }, model: { type: "string" }, role: { type: "string", enum: ["planner", "researcher", "coder"] } } }, default_config: { template: "" }, validation_rules: { alternatives: [["template", "prompt"]] }, output_schema: { fields: { content: "string", model: "string" } }, visual: { color: "#3b82f6", group: "leaf", icon: "MessageSquare" } },
  Tool: { config_schema: { type: "object", properties: { tool: { type: "string" }, args: { type: "object", additionalProperties: true } } }, default_config: { tool: "", args: {} }, validation_rules: { required: ["tool"] }, output_schema: { fields: { result: "any" } }, visual: { color: "#22c55e", group: "leaf", icon: "Wrench" } },
  Research: { config_schema: { type: "object", properties: { query: { type: "string", format: "textarea" }, depth: { type: "string", enum: ["quick", "standard", "deep"] }, max_sources: { type: "integer", minimum: 1, maximum: 50 }, private_kb: { type: "string" }, citation: { type: "boolean" } } }, default_config: { query: "", depth: "standard", max_sources: 10 }, validation_rules: { required: ["query"] }, output_schema: { fields: { summary: "string", notes: "array", sources: "array" } }, visual: { color: "#6366f1", group: "leaf", icon: "Search" } },
  Execution: { config_schema: { type: "object", properties: { task: { type: "string", format: "textarea" }, sandbox: { type: "string", enum: ["docker", "firecracker", "none"] }, max_steps: { type: "integer", minimum: 1, maximum: 200 }, allow_delegate: { type: "boolean" }, skills: { type: "array", items: { type: "string" } }, tools_whitelist: { type: "array", items: { type: "string" } } } }, default_config: { task: "", sandbox: "docker", max_steps: 20 }, validation_rules: { required: ["task"] }, output_schema: { fields: { output: "any", status: "string", artifacts: "array" } }, visual: { color: "#f97316", group: "leaf", icon: "Terminal" } },
  Coordinator: { config_schema: { type: "object", properties: { sub_agents: { type: "array", items: { type: "string" } }, planning_model: { type: "string" }, plan_hitl: { type: "boolean" }, replan: { type: "boolean" }, max_iterations: { type: "integer", minimum: 1, maximum: 20, default: 5 }, success_criteria: { type: "string", format: "textarea" }, skills: { type: "array", items: { type: "string" } } } }, default_config: { sub_agents: [], plan_hitl: false, max_iterations: 5 }, validation_rules: { ranges: { max_iterations: { min: 1, max: 20 } } }, output_schema: { fields: { achieved: "boolean", result: "any", iterations: "integer" } }, visual: { color: "#a855f7", group: "dynamic", icon: "🟣" } },
  Memory: { config_schema: { type: "object", properties: { action: { type: "string", enum: ["read", "write", "update", "delete", "summarize"] }, key: { type: "string" }, value: {}, scope: { type: "string", enum: ["scratch", "session", "long_term"] }, ttl_seconds: { type: "integer", minimum: 1 }, source_keys: { type: "array", items: { type: "string" } } } }, default_config: { action: "read", key: "" }, validation_rules: { required: ["action", "key"], enums: { action: ["read", "write", "update", "delete", "summarize"], scope: ["scratch", "session", "long_term"] } }, output_schema: { fields: { value: "any" } }, visual: { color: "#0ea5e9", group: "state", icon: "📦" } },
  Subworkflow: { config_schema: { type: "object", properties: { ref: { type: "string" }, inputs: { type: "object" }, version: { type: "string" }, timeout_seconds: { type: "integer", minimum: 1 } } }, default_config: { ref: "" }, validation_rules: { required: ["ref"] }, output_schema: { fields: { ref: "string", depth: "integer" } }, visual: { color: "#0ea5e9", group: "state", icon: "🔗" } },
  Knowledge: { config_schema: { type: "object", properties: { store: { type: "string" }, query: { type: "string", format: "textarea" }, top_k: { type: "integer", minimum: 1, maximum: 100, default: 5 }, rerank: { type: "string" }, filter: { type: "object" }, min_score: { type: "number", minimum: 0, maximum: 1 }, embedding: { type: "string" } } }, default_config: { store: "", query: "", top_k: 5 }, validation_rules: { required: ["store", "query"] }, output_schema: { fields: { chunks: "array", count: "integer" } }, visual: { color: "#14b8a6", group: "retrieval", icon: "📚" } },
};

let serverSchemas: Partial<Record<NodeType, NodeSchema>> = {};

export function mergeSchema(srv: Partial<Record<NodeType, NodeSchema>>): void {
  serverSchemas = srv;
}

export function getSchema(nt: NodeType): NodeSchema {
  return serverSchemas[nt] ?? FALLBACK_SCHEMAS[nt];
}
